
languageCode = 'en-us'
title = 'Помощь людям с ОВЗ: сайт для оказания экстренной помощи (I курс)'
theme = 'ananke'
[menu]
  [[menu.main]]
    name = "Главная"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "О проекте"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Участники"
    url = "/team/"
    weight = 3
  [[menu.main]]
    name = "Журнал"
    url = "/journal/"
    weight = 4
  [[menu.main]]
    name = "Ресурсы"
    url = "/resources/"
    weight = 5